### ISSUE TITLE
Ideas for Demos

### ISSUE THREAD

**Issue by mickeygousset** [devopselvis/github-actions-presentation#82]
- [ ] Environment input for manual workflow trigger
- [ ] respository_dispatch event demo
- [ ] Using a docker container in the "uses" statement
- [ ] Writing errors and warnings to log file
- [ ] Masking output in the log file
- [ ] Use the github-script action and core.summary to create fancy job summary
- [ ] Setting secrets and vars using gh
- [ ] semver vs calender versioning
